/* =========================================================
   PraxiSocIA — Traducteur visuel · dictionnaire des objets
   Les 80 classes reconnues par le modèle COCO-SSD, traduites
   à la main en 6 langues. Chaque entrée : label -> { langue: [mot, article/genre] }
   ========================================================= */

// Métadonnées des langues cibles (code = code voix Web Speech)
window.TV_LANGUES = {
  fr: { nom: "Français",  drapeau: "🇫🇷", voix: "fr-FR" },
  en: { nom: "English",   drapeau: "🇬🇧", voix: "en-US" },
  de: { nom: "Deutsch",   drapeau: "🇩🇪", voix: "de-DE" },
  es: { nom: "Español",   drapeau: "🇪🇸", voix: "es-ES" },
  it: { nom: "Italiano",  drapeau: "🇮🇹", voix: "it-IT" },
  pt: { nom: "Português", drapeau: "🇵🇹", voix: "pt-PT" }
};

// Traductions. Ordre des langues : fr, en, de, es, it, pt
// Clé = label anglais renvoyé par le modèle.
window.TV_DICO = {
  "person":        { fr:"une personne", en:"a person",     de:"eine Person",       es:"una persona",   it:"una persona",    pt:"uma pessoa" },
  "bicycle":       { fr:"un vélo",       en:"a bicycle",     de:"ein Fahrrad",       es:"una bicicleta", it:"una bicicletta", pt:"uma bicicleta" },
  "car":           { fr:"une voiture",   en:"a car",         de:"ein Auto",          es:"un coche",      it:"un'automobile",  pt:"um carro" },
  "motorcycle":    { fr:"une moto",      en:"a motorcycle",  de:"ein Motorrad",      es:"una moto",      it:"una moto",       pt:"uma moto" },
  "airplane":      { fr:"un avion",      en:"an airplane",   de:"ein Flugzeug",      es:"un avión",      it:"un aereo",       pt:"um avião" },
  "bus":           { fr:"un bus",        en:"a bus",         de:"ein Bus",           es:"un autobús",    it:"un autobus",     pt:"um autocarro" },
  "train":         { fr:"un train",      en:"a train",       de:"ein Zug",           es:"un tren",       it:"un treno",       pt:"um comboio" },
  "truck":         { fr:"un camion",     en:"a truck",       de:"ein Lastwagen",     es:"un camión",     it:"un camion",      pt:"um camião" },
  "boat":          { fr:"un bateau",     en:"a boat",        de:"ein Boot",          es:"un barco",      it:"una barca",      pt:"um barco" },
  "traffic light": { fr:"un feu de circulation", en:"a traffic light", de:"eine Ampel", es:"un semáforo", it:"un semaforo", pt:"um semáforo" },
  "fire hydrant":  { fr:"une bouche d'incendie", en:"a fire hydrant", de:"ein Hydrant", es:"una boca de incendios", it:"un idrante", pt:"um hidrante" },
  "stop sign":     { fr:"un panneau stop", en:"a stop sign", de:"ein Stoppschild",   es:"una señal de stop", it:"un segnale di stop", pt:"um sinal de stop" },
  "parking meter": { fr:"un parcmètre",  en:"a parking meter", de:"eine Parkuhr",    es:"un parquímetro", it:"un parchimetro", pt:"um parquímetro" },
  "bench":         { fr:"un banc",       en:"a bench",       de:"eine Bank",         es:"un banco",      it:"una panchina",   pt:"um banco" },
  "bird":          { fr:"un oiseau",     en:"a bird",        de:"ein Vogel",         es:"un pájaro",     it:"un uccello",     pt:"um pássaro" },
  "cat":           { fr:"un chat",       en:"a cat",         de:"eine Katze",        es:"un gato",       it:"un gatto",       pt:"um gato" },
  "dog":           { fr:"un chien",      en:"a dog",         de:"ein Hund",          es:"un perro",      it:"un cane",        pt:"um cão" },
  "horse":         { fr:"un cheval",     en:"a horse",       de:"ein Pferd",         es:"un caballo",    it:"un cavallo",     pt:"um cavalo" },
  "sheep":         { fr:"un mouton",     en:"a sheep",       de:"ein Schaf",         es:"una oveja",     it:"una pecora",     pt:"uma ovelha" },
  "cow":           { fr:"une vache",     en:"a cow",         de:"eine Kuh",          es:"una vaca",      it:"una mucca",      pt:"uma vaca" },
  "elephant":      { fr:"un éléphant",   en:"an elephant",   de:"ein Elefant",       es:"un elefante",   it:"un elefante",    pt:"um elefante" },
  "bear":          { fr:"un ours",       en:"a bear",        de:"ein Bär",           es:"un oso",        it:"un orso",        pt:"um urso" },
  "zebra":         { fr:"un zèbre",      en:"a zebra",       de:"ein Zebra",         es:"una cebra",     it:"una zebra",      pt:"uma zebra" },
  "giraffe":       { fr:"une girafe",    en:"a giraffe",     de:"eine Giraffe",      es:"una jirafa",    it:"una giraffa",    pt:"uma girafa" },
  "backpack":      { fr:"un sac à dos",  en:"a backpack",    de:"ein Rucksack",      es:"una mochila",   it:"uno zaino",      pt:"uma mochila" },
  "umbrella":      { fr:"un parapluie",  en:"an umbrella",   de:"ein Regenschirm",   es:"un paraguas",   it:"un ombrello",    pt:"um guarda-chuva" },
  "handbag":       { fr:"un sac à main", en:"a handbag",     de:"eine Handtasche",   es:"un bolso",      it:"una borsa",      pt:"uma mala de mão" },
  "tie":           { fr:"une cravate",   en:"a tie",         de:"eine Krawatte",     es:"una corbata",   it:"una cravatta",   pt:"uma gravata" },
  "suitcase":      { fr:"une valise",    en:"a suitcase",    de:"ein Koffer",        es:"una maleta",    it:"una valigia",    pt:"uma mala" },
  "frisbee":       { fr:"un frisbee",    en:"a frisbee",     de:"eine Frisbee",      es:"un frisbi",     it:"un frisbee",     pt:"um frisbee" },
  "skis":          { fr:"des skis",      en:"skis",          de:"Ski",               es:"unos esquís",   it:"degli sci",      pt:"uns esquis" },
  "snowboard":     { fr:"un snowboard",  en:"a snowboard",   de:"ein Snowboard",     es:"una tabla de snowboard", it:"uno snowboard", pt:"uma prancha de snowboard" },
  "sports ball":   { fr:"un ballon",     en:"a sports ball", de:"ein Ball",          es:"una pelota",    it:"un pallone",     pt:"uma bola" },
  "kite":          { fr:"un cerf-volant", en:"a kite",       de:"ein Drachen",       es:"una cometa",    it:"un aquilone",    pt:"um papagaio de papel" },
  "baseball bat":  { fr:"une batte de baseball", en:"a baseball bat", de:"ein Baseballschläger", es:"un bate de béisbol", it:"una mazza da baseball", pt:"um taco de basebol" },
  "baseball glove":{ fr:"un gant de baseball", en:"a baseball glove", de:"ein Baseballhandschuh", es:"un guante de béisbol", it:"un guanto da baseball", pt:"uma luva de basebol" },
  "skateboard":    { fr:"un skateboard", en:"a skateboard",  de:"ein Skateboard",    es:"un monopatín",  it:"uno skateboard", pt:"um skate" },
  "surfboard":     { fr:"une planche de surf", en:"a surfboard", de:"ein Surfbrett", es:"una tabla de surf", it:"una tavola da surf", pt:"uma prancha de surf" },
  "tennis racket": { fr:"une raquette de tennis", en:"a tennis racket", de:"ein Tennisschläger", es:"una raqueta de tenis", it:"una racchetta da tennis", pt:"uma raquete de ténis" },
  "bottle":        { fr:"une bouteille", en:"a bottle",      de:"eine Flasche",      es:"una botella",   it:"una bottiglia",  pt:"uma garrafa" },
  "wine glass":    { fr:"un verre à vin", en:"a wine glass", de:"ein Weinglas",      es:"una copa de vino", it:"un bicchiere di vino", pt:"um copo de vinho" },
  "cup":           { fr:"une tasse",     en:"a cup",         de:"eine Tasse",        es:"una taza",      it:"una tazza",      pt:"uma chávena" },
  "fork":          { fr:"une fourchette", en:"a fork",       de:"eine Gabel",        es:"un tenedor",    it:"una forchetta",  pt:"um garfo" },
  "knife":         { fr:"un couteau",    en:"a knife",       de:"ein Messer",        es:"un cuchillo",   it:"un coltello",    pt:"uma faca" },
  "spoon":         { fr:"une cuillère",  en:"a spoon",       de:"ein Löffel",        es:"una cuchara",   it:"un cucchiaio",   pt:"uma colher" },
  "bowl":          { fr:"un bol",        en:"a bowl",        de:"eine Schüssel",     es:"un cuenco",     it:"una ciotola",    pt:"uma tigela" },
  "banana":        { fr:"une banane",    en:"a banana",      de:"eine Banane",       es:"un plátano",    it:"una banana",     pt:"uma banana" },
  "apple":         { fr:"une pomme",     en:"an apple",      de:"ein Apfel",         es:"una manzana",   it:"una mela",       pt:"uma maçã" },
  "sandwich":      { fr:"un sandwich",   en:"a sandwich",    de:"ein Sandwich",      es:"un sándwich",   it:"un panino",      pt:"uma sanduíche" },
  "orange":        { fr:"une orange",    en:"an orange",     de:"eine Orange",       es:"una naranja",   it:"un'arancia",     pt:"uma laranja" },
  "broccoli":      { fr:"un brocoli",    en:"broccoli",      de:"Brokkoli",          es:"un brócoli",    it:"un broccolo",    pt:"um brócolo" },
  "carrot":        { fr:"une carotte",   en:"a carrot",      de:"eine Karotte",      es:"una zanahoria", it:"una carota",     pt:"uma cenoura" },
  "hot dog":       { fr:"un hot-dog",    en:"a hot dog",     de:"ein Hotdog",        es:"un perrito caliente", it:"un hot dog", pt:"um cachorro-quente" },
  "pizza":         { fr:"une pizza",     en:"a pizza",       de:"eine Pizza",        es:"una pizza",     it:"una pizza",      pt:"uma pizza" },
  "donut":         { fr:"un donut",      en:"a donut",       de:"ein Donut",         es:"una rosquilla", it:"una ciambella",  pt:"um donut" },
  "cake":          { fr:"un gâteau",     en:"a cake",        de:"ein Kuchen",        es:"un pastel",     it:"una torta",      pt:"um bolo" },
  "chair":         { fr:"une chaise",    en:"a chair",       de:"ein Stuhl",         es:"una silla",     it:"una sedia",      pt:"uma cadeira" },
  "couch":         { fr:"un canapé",     en:"a couch",       de:"ein Sofa",          es:"un sofá",       it:"un divano",      pt:"um sofá" },
  "potted plant":  { fr:"une plante en pot", en:"a potted plant", de:"eine Topfpflanze", es:"una planta en maceta", it:"una pianta in vaso", pt:"uma planta em vaso" },
  "bed":           { fr:"un lit",        en:"a bed",         de:"ein Bett",          es:"una cama",      it:"un letto",       pt:"uma cama" },
  "dining table":  { fr:"une table",     en:"a dining table", de:"ein Esstisch",     es:"una mesa",      it:"un tavolo",      pt:"uma mesa" },
  "toilet":        { fr:"des toilettes", en:"a toilet",      de:"eine Toilette",     es:"un inodoro",    it:"un gabinetto",   pt:"uma sanita" },
  "tv":            { fr:"une télévision", en:"a TV",         de:"ein Fernseher",     es:"un televisor",  it:"un televisore",  pt:"uma televisão" },
  "laptop":        { fr:"un ordinateur portable", en:"a laptop", de:"ein Laptop",    es:"un portátil",   it:"un portatile",   pt:"um portátil" },
  "mouse":         { fr:"une souris",    en:"a mouse",       de:"eine Maus",         es:"un ratón",      it:"un mouse",       pt:"um rato" },
  "remote":        { fr:"une télécommande", en:"a remote",   de:"eine Fernbedienung", es:"un mando",     it:"un telecomando", pt:"um comando" },
  "keyboard":      { fr:"un clavier",    en:"a keyboard",    de:"eine Tastatur",     es:"un teclado",    it:"una tastiera",   pt:"um teclado" },
  "cell phone":    { fr:"un téléphone",  en:"a cell phone",  de:"ein Handy",         es:"un móvil",      it:"un cellulare",   pt:"um telemóvel" },
  "microwave":     { fr:"un micro-ondes", en:"a microwave",  de:"eine Mikrowelle",   es:"un microondas", it:"un microonde",   pt:"um micro-ondas" },
  "oven":          { fr:"un four",       en:"an oven",       de:"ein Ofen",          es:"un horno",      it:"un forno",       pt:"um forno" },
  "toaster":       { fr:"un grille-pain", en:"a toaster",    de:"ein Toaster",       es:"una tostadora", it:"un tostapane",   pt:"uma torradeira" },
  "sink":          { fr:"un évier",      en:"a sink",        de:"ein Waschbecken",   es:"un fregadero",  it:"un lavandino",   pt:"um lava-loiça" },
  "refrigerator":  { fr:"un réfrigérateur", en:"a refrigerator", de:"ein Kühlschrank", es:"un frigorífico", it:"un frigorifero", pt:"um frigorífico" },
  "book":          { fr:"un livre",      en:"a book",        de:"ein Buch",          es:"un libro",      it:"un libro",       pt:"um livro" },
  "clock":         { fr:"une horloge",   en:"a clock",       de:"eine Uhr",          es:"un reloj",      it:"un orologio",    pt:"um relógio" },
  "vase":          { fr:"un vase",       en:"a vase",        de:"eine Vase",         es:"un jarrón",     it:"un vaso",        pt:"um vaso" },
  "scissors":      { fr:"des ciseaux",   en:"scissors",      de:"eine Schere",       es:"unas tijeras",  it:"delle forbici",  pt:"uma tesoura" },
  "teddy bear":    { fr:"un ours en peluche", en:"a teddy bear", de:"ein Teddybär",  es:"un osito de peluche", it:"un orsacchiotto", pt:"um urso de peluche" },
  "hair drier":    { fr:"un sèche-cheveux", en:"a hair dryer", de:"ein Föhn",        es:"un secador",    it:"un asciugacapelli", pt:"um secador" },
  "toothbrush":    { fr:"une brosse à dents", en:"a toothbrush", de:"eine Zahnbürste", es:"un cepillo de dientes", it:"uno spazzolino", pt:"uma escova de dentes" }
};
